INSERT INTO projet_io2.avis (id, autor_id, contenu, film)VALUES
(22, 63, 'J\'ai adoré !', 'Interstellar'),
(23, 63, 'Incroyable', 'Iron man 2'),
(24, 63, 'Bonne surprise, je le recommande', 'The Revenant'),
(25, 63, 'On me l\'a recommandé plus d\'une fois, à mon tour de vous le recommandé.', 'Les Affranchis'),
(26, 64, 'Une fin surprenant', 'Shutter Island'),
(27, 64, 'Un classique', 'Django'),
(28, 65, 'Sans plus', 'Uncharted'),
(29, 65, 'Pour un fan de la saga se film est un incontournable', 'Spider-Man-No-Way-Home'),
(30, 65, 'un film qui dure 3h mais on ne les voit pas passé', 'Les Huit Salopards'),
(31, 66, 'Excellent moment !', 'La Ruse'),
(32, 67, 'Un classique parmis tant d\'autres', 'Inception'),
(33, 67, 'Belle performance de Dicaprio', 'The Revenant'),
(34, 67, 'On peut le voir 10 fois,on s\'en lasse jamais', 'Les Affranchis'),
(35, 68, 'Ce film est encore mon préféré a ce jour', 'Interstellar'),
(36, 68, 'Moyennement convaincu mais néanmoins plutôt séduit par l’aspect esthétique lors d’un premier visionnage', 'Shutter Island'),
(37, 69, 'Le meilleur parmis la saga Iron Man', 'Iron man 2'),
(38, 69, 'Decu de la fin', 'Uncharted'),
(39, 71, 'Génial', 'Django');